---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170715141010"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170726190302"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "0496fd1a92fe4ae9c9469910670fe11f15ab37e4"
    sha: "0496fd1"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "springboot1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "springboot1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx2"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170728154124"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "7d4e39a66a028a8252247877cbfac3ff539d3bb0"
    sha: "7d4e39a"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx3"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "4048638c0f9941d771fbd8436204148b144ff3e5"
    sha: "4048638"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "sylvain-test3"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "4048638c0f9941d771fbd8436204148b144ff3e5"
    sha: "4048638"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "sylvain-test4"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.10-20170802170319"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "2b0664c20e421b9584ce077b7329811cb6c99e32"
    sha: "2b0664c"
  parameters:
    - "broadcaster": "spring-boot-seed"
    - "follower": "ddx10"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.8.0-20170810233312"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "c63956cf3ca1262455d9f2eca55cdd8c210f7835"
    sha: "c63956c"
  parameters:
    - "broadcaster": "springer-spaniel-seed"
    - "follower": "ddv1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170809213747"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.8.126-20170811204809"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "5f05a9884fbb4df3932ad053f09b66eb28633f0f"
    sha: "5f05a98"
  parameters:
    - "broadcaster": "spring-boot-seed"
    - "follower": "ddt1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.1"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "cef70139861a3dfc5cd1721fb0bc51903afed0f6"
    sha: "cef7013"
  parameters:
    - "broadcaster": "spring-boot-seed"
    - "follower": "blahdyblah"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.1"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "cef70139861a3dfc5cd1721fb0bc51903afed0f6"
    sha: "cef7013"
  parameters:
    - "broadcaster": "spring-boot-seed"
    - "follower": "projecty1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.1"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "cef70139861a3dfc5cd1721fb0bc51903afed0f6"
    sha: "cef7013"
  parameters:
    - "broadcaster": "spring-boot-seed"
    - "follower": "dds1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.1"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "cef70139861a3dfc5cd1721fb0bc51903afed0f6"
    sha: "cef7013"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "dd1-seed"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.17"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "master"
    sha: "0b53dce"
  parameters:
    - "broadcaster": "springer-spaniel-seed"
    - "follower": "testproj"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.17"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "master"
    sha: "0b53dce"
  parameters:
    - "broadcaster": "spring-rest-seed1"
    - "follower": "tanyatest11"
    - "featureName": "SpringBoot.Structure"

