---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170715141010"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170726190302"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "0496fd1a92fe4ae9c9469910670fe11f15ab37e4"
    sha: "0496fd1"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "springboot1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "springboot1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx1"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170727202817"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "94530c046256a6bfb832574805e3bd2d763161d6"
    sha: "94530c0"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx2"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9-20170728154124"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "7d4e39a66a028a8252247877cbfac3ff539d3bb0"
    sha: "7d4e39a"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "ddx3"
    - "featureName": "SpringBoot.Structure"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddFeatureFollowerEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "4048638c0f9941d771fbd8436204148b144ff3e5"
    sha: "4048638"
  parameters:
    - "broadcaster": "spring-rest-seed"
    - "follower": "sylvain-test3"
    - "featureName": "SpringBoot.Structure"

